#!/usr/bin/env python3
import argparse
import html
import json
import os
import re
from pathlib import Path

TEMPLATE = '''<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>{title}</title>
  <style>
    :root {{
      --bg: #0b1020;
      --panel: #121831;
      --panel-2: #1a2142;
      --text: #eef3ff;
      --muted: #9fb0d1;
      --accent: #7aa2ff;
      --accent-2: #67e8f9;
      --border: rgba(255,255,255,.09);
      --good: #22c55e;
      --warn: #f59e0b;
    }}
    * {{ box-sizing: border-box; }}
    body {{ margin:0; font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica,Arial,sans-serif; background:linear-gradient(180deg,#0a0f1d,#10162b); color:var(--text); }}
    .wrap {{ max-width: 980px; margin: 0 auto; padding: 20px; }}
    .hero {{ background: linear-gradient(135deg, rgba(122,162,255,.16), rgba(103,232,249,.08)); border:1px solid var(--border); border-radius: 22px; padding: 24px; box-shadow: 0 10px 30px rgba(0,0,0,.2); }}
    .eyebrow {{ color: var(--accent-2); font-size: 12px; text-transform: uppercase; letter-spacing: .12em; }}
    h1 {{ margin: 8px 0 12px; font-size: 28px; line-height: 1.2; }}
    .subtitle {{ color: var(--muted); font-size: 16px; line-height: 1.6; }}
    .grid {{ display:grid; grid-template-columns: repeat(auto-fit, minmax(240px, 1fr)); gap: 14px; margin-top: 18px; }}
    .card {{ background: rgba(255,255,255,.03); border:1px solid var(--border); border-radius: 18px; padding: 16px; }}
    .card h3 {{ margin: 0 0 8px; font-size: 16px; }}
    .muted {{ color: var(--muted); }}
    .chips {{ display:flex; gap:8px; flex-wrap:wrap; margin-top: 12px; }}
    .chip {{ background: rgba(122,162,255,.12); color:#dfe8ff; border:1px solid rgba(122,162,255,.22); border-radius: 999px; padding: 6px 10px; font-size: 12px; }}
    .section {{ margin-top: 22px; }}
    .section h2 {{ font-size: 20px; margin: 0 0 12px; }}
    .steps {{ display:grid; gap: 10px; }}
    .step {{ display:flex; gap: 12px; padding: 14px; background: var(--panel); border:1px solid var(--border); border-radius: 16px; }}
    .num {{ width: 28px; height: 28px; border-radius: 999px; background: var(--accent); color:#08101f; display:flex; align-items:center; justify-content:center; font-weight: 700; flex:0 0 auto; }}
    details {{ background: var(--panel); border:1px solid var(--border); border-radius: 16px; padding: 14px 16px; }}
    details + details {{ margin-top: 10px; }}
    summary {{ cursor:pointer; font-weight: 600; }}
    code, pre {{ font-family: ui-monospace,SFMono-Regular,Menlo,Monaco,Consolas,monospace; }}
    pre {{ background:#0a1020; color:#dbe7ff; border:1px solid var(--border); padding: 14px; border-radius: 14px; overflow:auto; white-space: pre-wrap; word-break: break-word; }}
    .footer {{ margin-top: 24px; color: var(--muted); font-size: 13px; }}
    .badge-good {{ color: var(--good); }}
    .badge-warn {{ color: var(--warn); }}
  </style>
</head>
<body>
  <div class="wrap">
    <div class="hero">
      <div class="eyebrow">Generative UI / Minis Prototype</div>
      <h1>{title}</h1>
      <div class="subtitle">{summary}</div>
      <div class="chips">{chips}</div>
      <div class="grid">
        <div class="card"><h3>核心判断</h3><div class="muted">{core_judgement}</div></div>
        <div class="card"><h3>当前可实现度</h3><div><span class="badge-good">可落地：</span>{feasible}</div></div>
        <div class="card"><h3>主要限制</h3><div><span class="badge-warn">受限：</span>{constraints}</div></div>
      </div>
    </div>

    <div class="section">
      <h2>实现路径</h2>
      <div class="steps">{steps}</div>
    </div>

    <div class="section">
      <h2>代码与组件</h2>
      {details_blocks}
    </div>

    <div class="footer">Generated by generative_ui_demo.py in Minis workspace.</div>
  </div>
</body>
</html>
'''

def esc(x):
    return html.escape(str(x))

def smart_split(text):
    lines = [x.strip(' -•\t') for x in re.split(r'[\n]+', text) if x.strip()]
    if len(lines) >= 3:
        return lines
    parts = [x.strip() for x in re.split(r'[。；;]+', text) if x.strip()]
    return parts or [text]

def build_spec(topic, text):
    bullets = smart_split(text)
    chips = [topic, '聊天内嵌 UI', 'HTML 原型', '可交互说明卡片']
    steps = [
        '从主题描述中提取结构化信息（摘要、要点、步骤、代码片段）',
        '将结构化结果映射到卡片、步骤流、折叠区块等 UI 组件',
        '生成单文件 HTML，在 Minis 中直接预览，模拟“生成式 UI”效果',
        '后续可叠加表单、筛选器、按钮回调、图表与多页面状态'
    ]
    return {
        'title': f'{topic}：生成式 UI 落地原型',
        'summary': '把文本回答转成可视化信息卡、步骤流和折叠详情，是当前环境下最稳妥的 Claude 式生成式 UI 复刻路线。',
        'chips': chips,
        'core_judgement': '本质是“模型输出结构 + 前端动态渲染”，不是单纯排版优化。重点在于让回答天然变成界面。',
        'feasible': '可以通过 Python 直接生成自包含 HTML，并在 Minis 里作为可点击预览打开。',
        'constraints': '当前无法直接修改聊天宿主的原生消息渲染层，因此更适合做外部 HTML artifact / 卡片式页面。',
        'steps': steps,
        'details': [
            {'title': '推文思路还原', 'content': '\n'.join(bullets[:8])},
            {'title': '当前环境的最优实现', 'content': '输入：文本主题/说明 → Python 提取结构 → 输出 HTML 页面 → 在 Minis 中预览/分享。'},
            {'title': '后续增强方向', 'content': '1. 接模型生成 JSON spec\n2. 支持图表/表格/时间线\n3. 表单交互\n4. 多模板自动选择\n5. 与具体 skill 结合'}
        ]
    }

def render(spec):
    chips = ''.join(f'<span class="chip">{esc(c)}</span>' for c in spec['chips'])
    steps = ''.join(
        f'<div class="step"><div class="num">{i}</div><div>{esc(s)}</div></div>'
        for i, s in enumerate(spec['steps'], 1)
    )
    details_blocks = ''.join(
        f'<details open><summary>{esc(d["title"])}</summary><pre>{esc(d["content"])}</pre></details>'
        for d in spec['details']
    )
    return TEMPLATE.format(
        title=esc(spec['title']),
        summary=esc(spec['summary']),
        chips=chips,
        core_judgement=esc(spec['core_judgement']),
        feasible=esc(spec['feasible']),
        constraints=esc(spec['constraints']),
        steps=steps,
        details_blocks=details_blocks,
    )

def main():
    ap = argparse.ArgumentParser(description='Generate a Claude-like generative UI HTML prototype.')
    ap.add_argument('topic', help='Topic title')
    ap.add_argument('--text', default='', help='Source text / notes to structure into UI')
    ap.add_argument('--spec', help='Optional JSON spec file path')
    ap.add_argument('--out', default='/var/minis/workspace/generative_ui_demo.html', help='Output HTML path')
    args = ap.parse_args()

    if args.spec:
        spec = json.loads(Path(args.spec).read_text(encoding='utf-8'))
    else:
        spec = build_spec(args.topic, args.text or args.topic)

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render(spec), encoding='utf-8')
    print(json.dumps({'status': 'ok', 'output': str(out)}, ensure_ascii=False))

if __name__ == '__main__':
    main()
