export const DEFAULT_PORT = 8787;
export const MAX_BODY_BYTES = 8 * 1024 * 1024;
export const MAX_OUTPUT_BYTES = 1024 * 1024;
export const MAX_SESSION_EVENTS = 300;
export const VERSION = "0.1.31";
export const RUNTIME_SOURCE = "ocli";
export const BRIDGE_NAME = "Oases desktop bridge";

export const PROJECT_TOOL_NAMES = new Set([
  "list_files",
  "glob_files",
  "search_files",
  "grep_files",
  "workspace_status",
  "worktree_list",
  "worktree_diff",
  "worktree_apply",
  "worktree_remove",
  "read_file",
  "write_file",
  "edit_file",
  "delete_file",
  "fetch_url",
  "web_search",
  "mcp_list",
  "mcp_call",
  "mcp_resources_list",
  "mcp_resource_read",
  "run_command",
  "run_python",
  "todo_write",
  "todo_read",
  "settings_list",
  "settings_read",
  "settings_write",
  "capability_route_preview",
  "memory_list",
  "memory_search",
  "memory_read",
  "memory_write",
  "command_list",
  "command_read",
  "output_style_list",
  "output_style_read",
  "skill_list",
  "skill_read",
  "skill_asset_list",
  "skill_asset_read",
  "skill_install",
  "plugin_list",
  "plugin_read",
  "plugin_capability_list",
  "plugin_capability_read",
  "plugin_command_list",
  "plugin_command_read",
  "plugin_command_install",
  "plugin_output_style_list",
  "plugin_output_style_read",
  "plugin_output_style_install",
  "plugin_hook_list",
  "plugin_hook_read",
  "plugin_agent_list",
  "plugin_agent_read",
  "plugin_agent_install",
  "plugin_skill_list",
  "plugin_skill_read",
  "plugin_skill_install",
  "plugin_asset_list",
  "plugin_asset_read",
  "plugin_install",
  "plugin_remove",
  "plugin_enable",
  "plugin_disable",
  "agent_list",
  "agent_read",
  "agent_write",
  "agent_framework_list",
  "agent_framework_read",
  "agent_framework_write",
  "agent_run",
  "agent_status",
]);
